### ISSUE TITLE
Uncaught mysqli_sql_exception in module_sql.php

### ISSUE THREAD

**Issue by Darkseid1981** [pivotx/PivotX#11]
I tried to add categories on my offline server (xampp) and got a blank page. So I checked the php error log. This after updating to the latest master. here is the php error log: 
[php_error_log.txt](https://github.com/pivotx/PivotX/files/11675971/php_error_log.txt)

Looks like one solution leads to another bug. Sorry, I feel like I'm wasting your time with all these annoying bugs, when I'm trying out all of the pivotx features.

**Comment by hansfn** [comment]
This is a bug. Thx for the report. (It's not a support question.)

**Comment by hansfn** [comment]
Just for the record: The bug was introduced when fixing all the "Undefined array key" notices reported by PHP 8.

In addition to fixing the introduced bug, ref commit above, the code was improved for the specific case were only entries are counted.
