### ISSUE TITLE
 Uncaught ArgumentCountError: Too few arguments to function smarty_calendar() in module_extensions.php

### ISSUE THREAD

**Issue by Darkseid1981** [pivotx/PivotX#13]
This one is an unexpected bug, it also makes the two and three column and skinny template render incorrectly. Here is the error log: 
[php_error_log.txt](https://github.com/pivotx/PivotX/files/11710022/php_error_log.txt)

This one came about after I tried the entry calendar widget. I want to use in in my theme, but as long as it does this I'll have to wait for fix, before I can try and add widgets to my template.

**Comment by hansfn** [comment]
Hi!

This is a bug in the [calendar extension](https://github.com/pivotx/PivotX-extensions/tree/master/calendar) which isn't included with the PivotX core. It looks like the extension hasn't been updated for 10 years ... Please file the bug in the [extension repository](https://github.com/pivotx/PivotX-extensions).

PS! Please include the error log as text, not as an attachment. If you insert the text, select it and then click the "Add code" button you get the display that we want - one single block of code / error message.
