### ISSUE TITLE
Fatal Errors and some curiosities

### ISSUE THREAD

**Issue by Lemuria3** [pivotx/PivotX#17]
Web server: Apache/2.4 Server API CGI/FastCGI
Server default charset: UTF-8
PHP Version: 8.2.7
PivotX version from Commits on Jun 26, 2023

A few test results:
New clean Setup, Frontend and login to PivotX works without any PHP errors. 

When creating a blog entry, the following happens depending on error_reporting:

Error_reporting: Development Value: E_ALL
-----------------------------------------------
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../pivotx/pivotx/ajaxhelper.php on line 864
- Fatal error: Uncaught Error: Cannot access private property EntriesFlat::$entry in ../pivotx/pivotx/modules/module_db.php:483
- Fatal error: Uncaught TypeError: array_intersect():  Argument # 1 ($array) must be of type array, null given in ../pivotx/pivotx/modules/entries_flat.php:833 

(Edited by hansfn to preserved a bare minimum to fix issues.)

Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT 
---------------------------------------------------------------
Logged in and editing an entry, work...

After press the Save Button: 

We are sorry, (HTTP) 500 Internal Server Error

**Comment by hansfn** [comment]
It's the same error caught at different times.
