### ISSUE TITLE
Pivotx archive pagetype (smarty templating)

### ISSUE THREAD

**Issue by bcmans** [pivotx/PivotX#21]
Web server: Apache/2.4 Server API CGI/FastCGI
Server default charset: UTF-8
PHP Version: 8.2.7
PivotX version from Commits on Jun 26, 2023

A few test results:
New clean Setup, Frontend and login to PivotX works without any PHP errors.

When using [[ if $modifier.pagetype=="full-archive" ]] or [[ if $modifier.pagetype=="full-archive" ]] i am not getting the result i want. Read: how to filter on pagetype is archive.

Does someone know what i should be using?
Thanks!

**Comment by bcmans** [comment]
solved it with the use of [[ if (!empty($modifier.archive)) ]]

**Comment by hansfn** [comment]
Great that you solved it yourself. This is probably also a side effect of the changes in PHP 8. I'll see if we can set a default (empty) value so we don't have to add these not empty tests all over in the Smarty template.
