### ISSUE TITLE
Can't post comments "Fatal error: Uncaught Error: Cannot access private property"

### ISSUE THREAD

**Issue by brainexcerpts** [pivotx/PivotX#24]
Posting a comment results in:

```
Fatal error: Uncaught Error: Cannot access private property  thrown in \www\pivotx\modules\module_comments.php on line 157
```

This is likely due to the recent refactoring of pivotx/objects.php that now explicitly declare attributes as private 
I guess before they were defined inside the methods which implicitly made them public.

I'm not sure what is the best course of action. For now I'm making them public (line 1986 of pivotx/objects.php)

**Comment by hansfn** [comment]
This happens to me only when previewing before posting. Do you experience it when posting directly?
