### ISSUE TITLE
Unsupported operand types: int + string in forms.php

### ISSUE THREAD

**Issue by Darkseid1981** [pivotx/PivotX#5]
OK, so now every thing works great until I click on save. I get the new weblog form but after clicking the save button I get a blank page. The PHP_error_log now has this:

`[30-May-2023 15:04:01 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int + string in /opt/lampp/htdocs/projects/pivotx-3/pivotx/forms.php:1628`
`Stack trace:`
`#0 /opt/lampp/htdocs/projects/pivotx-3/pivotx/pages.php(3152): getWeblogForm3('fanfics')`
`#1 /opt/lampp/htdocs/projects/pivotx-3/pivotx/pages.php(2010): pageWeblogedit()`
`#2 /opt/lampp/htdocs/projects/pivotx-3/pivotx/lib.php(272): pageWeblognew()`
`#3 /opt/lampp/htdocs/projects/pivotx-3/pivotx/index.php(21): displayPage()`
`#4 {main}`
`  thrown in /opt/lampp/htdocs/projects/pivotx-3/pivotx/forms.php on line 1628`

Do I have to paste all of this or just the first line?

**Comment by hansfn** [comment]
Will fix later today. I did actually test saving a new weblog, but only for the "Bare Bones" theme. That theme lacks the settings that causes the error you see.

**Comment by hansfn** [comment]
[Fixed](https://github.com/pivotx/PivotX/commit/fa87fa75cc8c1182171c296d243545160b051070).

PS! Please give the issues useful titles so it's easy to find for other people. (I edited this issue.)
